### ISSUE TITLE
No root access?

### ISSUE THREAD

**Issue by rngnrs** [vollborn/jetbrains-gateway-ssh#1]
I need to install some packages (i.e. Node, npm, ffmpeg, Redis...) but the image does not contain `sudo` package or root access.
I can't use `SSH_USERNAME = root` as well because this user already exists.

I think this image is useless in its current state because lack of apps and ability to install them.
Is there any possibility to tweak this image to obtain root privileges?

**Comment by rngnrs** [comment]
Solution:

- Attach the container to a console (`docker attach <id>`) and set a password for `root` via `passwd`.
- Run a privileged session by typing `su root` from client terminal.
- Install necessary packages and exit the session.
- Repeat these steps after each creation of the container.
- ...
- PROFIT

**Comment by vollborn** [comment]
Hey there! Personally I would build a custom image based on vollborn/jetbrains-gateway-ssh instead of running the commands on startup, if I wanted to add some dependencies. Something along the lines of...

```dockerfile
FROM vollborn/jetbrains-gateway-ssh

RUN apt-get install node redis -y
```

Your dependencies should now be installed on every startup, without running additional commands.

But you're right, logging in as root using SSH is currently not possible. I think it's part of the default configuration of the SSH server. Just tried a few things, update is coming soon.
